import { StyleSheet } from "react-native";

const blue = "#2F67C8";
const text = "#151515";

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F4F4",
  },
  listContent: {
    paddingBottom: 118,
  },
  header: {
    alignItems: "center",
    backgroundColor: blue,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    minHeight: 214,
    paddingHorizontal: 22,
    paddingTop: 70,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
    elevation: 12,
  },
  welcome: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "500",
    letterSpacing: 0,
    textAlign: "center",
    writingDirection: "rtl",
  },
  locationRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 7,
  },
  locationPin: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 17,
    marginRight: 7,
  },
  locationText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "500",
    letterSpacing: 0,
    textAlign: "center",
    writingDirection: "rtl",
  },
  searchBar: {
    alignItems: "center",
    backgroundColor: "#F0F0F2",
    borderRadius: 22,
    bottom: -28,
    flexDirection: "row",
    height: 48,
    left: 22,
    paddingHorizontal: 17,
    position: "absolute",
    right: 22,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.32,
    shadowRadius: 10,
    elevation: 10,
  },
  searchIcon: {
    color: "#000000",
    fontSize: 28,
    fontWeight: "500",
    lineHeight: 30,
    marginRight: 8,
  },
  searchInput: {
    color: text,
    flex: 1,
    fontSize: 14,
    height: "100%",
    paddingHorizontal: 8,
    textAlign: "right",
    writingDirection: "rtl",
  },
  clearSearch: {
    color: "#6D6D6D",
    fontSize: 24,
    fontWeight: "600",
    paddingLeft: 10,
  },
  content: {
    paddingHorizontal: 0,
    paddingTop: 42,
  },
  sectionTitle: {
    color: text,
    fontSize: 18,
    fontWeight: "500",
    letterSpacing: 0,
    marginBottom: 16,
    marginTop: 0,
    paddingHorizontal: 24,
    textAlign: "right",
    writingDirection: "rtl",
  },
  sportsList: {
    alignItems: "center",
    gap: 20,
    paddingHorizontal: 18,
    paddingBottom: 18,
  },
  sportItem: {
    alignItems: "center",
    justifyContent: "center",
    width: 66,
  },
  sportCircle: {
    alignItems: "center",
    borderRadius: 43,
    height: 86,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.3,
    shadowRadius: 9,
    width: 86,
    elevation: 9,
  },
  sportCircleActive: {
    borderColor: "#000000",
    borderWidth: 3,
  },
  sportIcon: {
    color: "#000000",
    fontSize: 35,
    lineHeight: 39,
  },
  sportLabel: {
    color: "#222222",
    fontSize: 12,
    fontWeight: "500",
    marginTop: 8,
    textAlign: "center",
    writingDirection: "rtl",
  },
  hint: {
    color: "#D42626",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
    paddingHorizontal: 24,
    textAlign: "center",
    writingDirection: "rtl",
  },
  loadingBox: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    marginHorizontal: 22,
    paddingVertical: 22,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.16,
    shadowRadius: 9,
    elevation: 7,
  },
  loadingText: {
    color: "#333333",
    fontSize: 14,
    marginTop: 8,
    textAlign: "center",
    writingDirection: "rtl",
  },
  fieldCard: {
    alignItems: "stretch",
    backgroundColor: "#FFFFFF",
    flexDirection: "row-reverse",
    height: 156,
    marginBottom: 14,
    marginHorizontal: 0,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 8,
  },
  fieldImage: {
    height: 156,
    width: 150,
  },
  fieldInfo: {
    flex: 1,
    justifyContent: "center",
    paddingLeft: 16,
    paddingRight: 24,
  },
  fieldTitle: {
    color: blue,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 20,
    marginBottom: 9,
    textAlign: "right",
    writingDirection: "rtl",
  },
  fieldDistance: {
    color: text,
    fontSize: 12,
    lineHeight: 19,
    marginBottom: 2,
    textAlign: "right",
    writingDirection: "rtl",
  },
  fieldAddress: {
    color: "#5D5D5D",
    fontSize: 11,
    lineHeight: 17,
    marginBottom: 11,
    textAlign: "right",
    writingDirection: "rtl",
  },
  bookButton: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: blue,
    borderRadius: 12,
    height: 31,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 5,
    elevation: 5,
  },
  bookButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
    writingDirection: "rtl",
  },
  footer: {
    paddingHorizontal: 22,
    paddingTop: 8,
  },
  loadMoreButton: {
    alignItems: "center",
    backgroundColor: blue,
    borderRadius: 14,
    height: 42,
    justifyContent: "center",
  },
  disabledButton: {
    opacity: 0.55,
  },
  loadMoreText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    writingDirection: "rtl",
  },
  bottomNav: {
    alignItems: "center",
    backgroundColor: "#EEF3FF",
    borderTopLeftRadius: 31,
    borderTopRightRadius: 31,
    bottom: 0,
    flexDirection: "row",
    height: 76,
    justifyContent: "space-around",
    left: 0,
    paddingBottom: 12,
    paddingHorizontal: 58,
    position: "absolute",
    right: 0,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 12,
  },
  navItem: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    width: 76,
  },
  navIcon: {
    color: "#9F9F9F",
    fontSize: 33,
    fontWeight: "900",
    lineHeight: 36,
  },
  navIconActive: {
    color: blue,
  },
});
