import { StyleSheet } from "react-native";

const blue = "#2F67C8";

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F6F6F6",
  },
  content: {
    paddingBottom: 34,
  },
  loadingScreen: {
    alignItems: "center",
    backgroundColor: "#F6F6F6",
    flex: 1,
    justifyContent: "center",
  },
  loadingText: {
    color: "#333333",
    fontSize: 15,
    marginTop: 10,
    textAlign: "center",
    writingDirection: "rtl",
  },
  header: {
    backgroundColor: blue,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    height: 203,
    paddingHorizontal: 22,
    paddingTop: 44,
  },
  backButton: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  backText: {
    color: "#FFFFFF",
    fontSize: 42,
    lineHeight: 42,
  },
  avatarWrap: {
    alignSelf: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 86,
    height: 172,
    justifyContent: "center",
    marginTop: -86,
    padding: 5,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    width: 172,
    elevation: 9,
  },
  avatar: {
    borderRadius: 81,
    height: 162,
    width: 162,
  },
  avatarFallback: {
    alignItems: "center",
    backgroundColor: "#DFE8FF",
    borderRadius: 81,
    height: 162,
    justifyContent: "center",
    width: 162,
  },
  avatarInitial: {
    color: blue,
    fontSize: 58,
    fontWeight: "900",
  },
  name: {
    color: "#111111",
    fontSize: 30,
    fontWeight: "900",
    letterSpacing: 0,
    marginTop: 15,
    textAlign: "center",
    writingDirection: "rtl",
  },
  emailPill: {
    alignSelf: "center",
    backgroundColor: "#D9D9D9",
    borderRadius: 14,
    color: "#333333",
    fontSize: 14,
    marginTop: 8,
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingVertical: 4,
    textAlign: "center",
  },
  actionsRow: {
    alignItems: "center",
    flexDirection: "row-reverse",
    gap: 10,
    justifyContent: "center",
    marginTop: 18,
    paddingHorizontal: 24,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: blue,
    borderRadius: 13,
    height: 40,
    justifyContent: "center",
    minWidth: 132,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    writingDirection: "rtl",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#E9F0FF",
    borderColor: blue,
    borderRadius: 13,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    minWidth: 82,
    paddingHorizontal: 15,
  },
  secondaryButtonText: {
    color: blue,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
    writingDirection: "rtl",
  },
  card: {
    backgroundColor: "#FFFFFF",
    marginTop: 18,
    paddingHorizontal: 24,
    paddingVertical: 16,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 5,
  },
  cardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  cardTitle: {
    color: "#111111",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
    textAlign: "right",
    writingDirection: "rtl",
  },
  editText: {
    color: blue,
    fontSize: 15,
    fontWeight: "800",
    writingDirection: "rtl",
  },
  infoRow: {
    alignItems: "center",
    borderBottomColor: "#ECECEC",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 43,
  },
  infoLabel: {
    color: "#222222",
    fontSize: 15,
    fontWeight: "700",
    textAlign: "right",
    writingDirection: "rtl",
  },
  infoValue: {
    color: "#555555",
    flex: 1,
    fontSize: 15,
    marginRight: 16,
    textAlign: "left",
  },
  inputGroup: {
    marginTop: 10,
  },
  inputLabel: {
    color: "#222222",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 7,
    textAlign: "right",
    writingDirection: "rtl",
  },
  input: {
    backgroundColor: "#EFEFEF",
    borderRadius: 13,
    color: "#111111",
    fontSize: 16,
    height: 49,
    paddingHorizontal: 15,
  },
  editActions: {
    flexDirection: "row-reverse",
    gap: 10,
    marginTop: 14,
  },
  saveDetailsButton: {
    alignItems: "center",
    backgroundColor: blue,
    borderRadius: 13,
    flex: 1,
    height: 44,
    justifyContent: "center",
  },
  saveDetailsText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    writingDirection: "rtl",
  },
  cancelButton: {
    alignItems: "center",
    backgroundColor: "#EEEEEE",
    borderRadius: 13,
    flex: 1,
    height: 44,
    justifyContent: "center",
  },
  cancelText: {
    color: "#333333",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    writingDirection: "rtl",
  },
  passwordButton: {
    alignItems: "center",
    backgroundColor: blue,
    borderRadius: 13,
    height: 45,
    justifyContent: "center",
    marginTop: 15,
  },
  passwordButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    writingDirection: "rtl",
  },
  errorText: {
    color: "#D42626",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 14,
    paddingHorizontal: 24,
    textAlign: "center",
    writingDirection: "rtl",
  },
  successText: {
    color: "#1E8E3E",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 14,
    paddingHorizontal: 24,
    textAlign: "center",
    writingDirection: "rtl",
  },
});
